[2023-09-27 04:59:38,521] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:59:49,684] INFO _log() L224   * Detected change in 'C:\\Users\\fadami\\Desktop\\pucBackEndAvançado\\app.py', reloading - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 04:59:49,866] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:02,405] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.3:5000 (Press CTRL+C to quit) - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:02,408] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:10,129] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:10,225] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:10] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:10,381] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:10] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:10,475] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:10] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:11,532] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:11] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:11,547] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:11] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:11,792] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:11] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:11,856] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:11] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:12,358] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:12] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:30,059] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 05:00:30,059] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:30] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:30,964] WARNING update_pessoa() L165  Erro ao adicionar pessoa 'João Neto', Não foi possível salvar novo item :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L165 
[2023-09-27 05:00:30,965] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:30] "[31m[1mPUT /pessoas HTTP/1.1[0m" 400 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:49,607] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:49] "DELETE /pessoa?nome=João%20Neto HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:51,192] WARNING del_pessoa() L94   Erro ao deletar pessoa #'João Neto', Pessoa não encontrado na base :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L94  
[2023-09-27 05:00:51,194] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:51] "[33mDELETE /pessoa?nome=João%20Neto HTTP/1.1[0m" 404 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:00:57,589] WARNING del_pessoa() L94   Erro ao deletar pessoa #'João Neto', Pessoa não encontrado na base :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L94  
[2023-09-27 05:00:57,590] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:00:57] "[33mDELETE /pessoa?nome=João%20Neto HTTP/1.1[0m" 404 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:01:25,531] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.3:5000 (Press CTRL+C to quit) - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:01:25,536] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:10,445] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:10,651] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:10] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:10,673] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:10] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:10,856] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:10] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:15,220] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:15] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:15,252] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:15] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:15,471] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:15] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:15,575] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:15] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:16,100] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:16] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:41,399] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:41] "POST /pessoa HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:06:43,438] WARNING add_pessoa() L123  Erro ao adicionar pessoa 'João Neto', Pessoa de mesmo nome já salvo na base :/ - call_trace=C:\Users\fadami\Desktop\pucBackEndAvançado\app.py L123 
[2023-09-27 05:06:43,440] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:06:43] "[31m[1mPOST /pessoa HTTP/1.1[0m" 409 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:07:06,377] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:07:06] "GET /pessoas HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:07:07,800] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:07:07] "GET /pessoas HTTP/1.1" 200 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:07:18,143] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:07:18] "[35m[1mGET /pessoa?nome=João%20Neto HTTP/1.1[0m" 500 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-27 05:07:19,846] INFO _log() L224  127.0.0.1 - - [27/Sep/2023 05:07:19] "[35m[1mGET /pessoa?nome=João%20Neto HTTP/1.1[0m" 500 - - call_trace=C:\Users\fadami\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
